FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        curl \
        nano \
        wget \
        unzip \
        ca-certificates \
		jq \
        locales \
        apt-transport-https \
        software-properties-common \
        sudo \
        tmux
       

# Install Docker 
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
	apt-key fingerprint 0EBFCD88 && \ 
	add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   						$(lsb_release -cs) \
   						stable" &&\
   	apt-get update && apt-get install -y --no-install-recommends docker-ce
   
   
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY environment.yml .
COPY azure_requirements.txt .

ENV ENV_NAME=py36
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda env create -q --name $ENV_NAME -f environment.yml && \
     /opt/conda/bin/conda clean -ya && \
     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \ 
     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \ 
     echo "conda activate $ENV_NAME" >> ~/.bashrc
ENV PATH /opt/conda/envs/$ENV_NAME/bin:/opt/conda/bin:$PATH

RUN ["/bin/bash", "-c", "pip install -r azure_requirements.txt --ignore-installed PyYAML"]

# Install Azure CLI
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ xenial main" | \
    tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
     --keyserver packages.microsoft.com \
     --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    azure-cli

RUN az extension add -n azure-cli-ml # Install azure ml extension

# Install AzCopy
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/ xenial main" > azure.list &&\
	cp ./azure.list /etc/apt/sources.list.d/ &&\
	apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893 &&\
	apt-get update &&\
	apt-get install -y --no-install-recommends azcopy

COPY jupyter_notebook_config.py /root/.jupyter/

SHELL ["/bin/bash", "-c"]
RUN jupyter nbextension install --py --user azureml.widgets && \
	jupyter nbextension enable --py --user azureml.widgets

# Adding nvidia-docker alias
RUN echo -e '#!/bin/bash\ndocker "$@"' > /usr/bin/nvidia-docker && \
    chmod +x /usr/bin/nvidia-docker

ENV PYTHONPATH /workspace/scripts:/workspace/control/src:$PYTHONPATH
# template {% if cookiecutter.type == "template" or cookiecutter.type == "all"%}
ENV PYTHONPATH /workspace/TensorFlow_experiment:$PYTHONPATH 
# ------ {% endif %}
# benchmark {% if cookiecutter.type == "benchmark" or cookiecutter.type == "all"%}
ENV PYTHONPATH /workspace/TensorFlow_benchmark:$PYTHONPATH 
# ------ {% endif %}
# imagenet {% if cookiecutter.type == "imagenet" or cookiecutter.type == "all"%}
ENV PYTHONPATH /workspace/TensorFlow_imagenet:$PYTHONPATH 
# ------- {% endif %}
# pytorch benchmark {% if cookiecutter.type == "pytorch_benchmark" or cookiecutter.type == "all"%}
ENV PYTHONPATH /workspace/PyTorch_benchmark:$PYTHONPATH 
# ------- {% endif %}
# pytorch imagenet {% if cookiecutter.type == "pytorch_imagenet" or cookiecutter.type == "all"%}
ENV PYTHONPATH /workspace/PyTorch_imagenet:$PYTHONPATH 
# ------- {% endif %}
# Completion script
COPY bash.completion /etc/bash_completion.d/
RUN echo "source /etc/bash_completion.d/bash.completion" >> /root/.bashrc
# Tmux
COPY tmux.conf /root/.tmux.conf
WORKDIR /workspace
CMD /bin/bash